language: node_js
node_js:
  - lts/dubnium
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: wg6+ISTzzh5Qov9f4KdO7Kt89IG3Lg8EEi3fcAx0/39kCxQmNSsPeDfl47++TAuNNkCqS36/rpV5MQPNX/V83O7UsPg9UurdGb5xEQwukK0eXHeO7aPsQW1F9+vGnirz5yreO/AnQF6w0ofFMZYndDvYzpm+Y1T0oKrHMJ8grIRg2FxzK+Rcw4Su74a9oHTkzzHsBndHQogFH1gW1L6iES36YdM5AVVP/1KgzPfSvp7ZF1iGfz/EHQqrCxC1UHwX7BLFWyUcBbo36iSVeVnEe1L5O+5Y7eL2vIKNcex3yCy0OJoQ4NS05kGEwLZR8czZfOzN0halaLxUdKNZocqsetMrv2Xcd4nTPVLWwRH+Enh1sA8FtSPyWbwqvrm/hiKPUG9w8LqWt0aa73vdAq0dZenQ2u2hz7z9817ljPq+CxG+R0jPG8qDQUU+8cuIzrQOMQINzUQgZZpFIScKwJAzgTNDIa1w8PDtPHdy48uOKG9QYHW4NCLhnSqhEsFnI07DhBmr/Me/9JA8CDaXSbY1GnBWGJ2xP7l5P1Csiyj4j6Wu8rg4aOcqlkf0tvD4MGpOxJtgmwG0n+XoW92r6xiPrnAd0M+7sGDMTOfaxMxUza0IROq4eQmESyUAHRkr+iZ/G2heRN0DKZlYpIGHQAnecu9J/l01XPP9c8sCdGNuGno=
  file:
    - 'svg-event-attributes.js'
    - 'svg-event-attributes.min.js'
  on:
    tags: true
